name: Deploy to Fly.io
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Forçar criação do Volume
        # Tentamos criar um único volume e ignoramos se der erro
        run: flyctl volumes create whatsapp_data --region iad --size 1 -a whatsapp-bridge-api --non-interactive || true
        
      - name: Deploy Forçado
        # O segredo aqui é o "--ha=false" e o "--strategy immediate"
        run: flyctl deploy --remote-only --ha=false --strategy immediate -a whatsapp-bridge-api


